# fluent-bit-3.2.10/conf/fluent-bit.conf

[SERVICE]
    Flush        1
    Log_Level    info
    # 압축 푼 폴더 내부 기준 또는 절대 경로로 parsers.conf를 지정해야 multiline이 작동합니다.
    Parsers_File /home/1180515/fluent-bit-3.2.10/conf/parsers.conf
    
# 1. 여러 경로에서 로그 수집 (Wildcard * 사용 가능)
[INPUT]
    Name         tail
    # 여러 경로 지정
    Path         /hli_app/log/was/DEV_PICA_HPF/nohup/*.log,/hli_app/log/was/DEV_PICA_HGW/nohup/*.log,/hli_app/log/pica/hbt/hpf/*.log,/hli_app/log/pica/hbt/hms/*.log
    Tag          app.logs
    # 에러가 발생했을 때 뒤따라오는 Stack Trace들을 한 덩어리로 묶는 규칙 호출
    Multiline.parser go, java, python 
    # 로그 읽은 위치를 기억하는 체크포인트 파일 지정
    db           /home/1180515/fluent-bit-tail.db

# 2. 필터링: Exception이나 Error가 포함된 로그만 통과시키기
[FILTER]
    Name         grep
    Match        app.logs
    # log라는 필드 안에서 대소문자 구분 없이 error 또는 exception이 포함된 것만 필터링
    Regex        log (?i)(error|exception)

# 3. 최종 목적지: 귀하의 DB 저장용 API URL로 전송
[OUTPUT]
    Name         http
    Match        app.logs
    # 보통 VirtualBox의 NAT 네트워크 환경에서 윈도우(호스트)는 10.0.2.2
    Host         10.0.2.2
    Port         8080
    URI          /fluent-bit/logs/collect
    Format       json