#??? ?? ????
#vi config/server.properties



# ???? ??? ? ???? ??    `localhost`
# ?????? ???? ??? ? ???? IP ??? ??? ??. ??? EC2? Public IP ??? ??????.
advertised.listeners=PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093